/*.$file${../qm_generated::dishwasher_sm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_controller.qm
* File:  ${../qm_generated::dishwasher_sm.h}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::dishwasher_sm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef DISHWASHERCONTROLLER_SM_H
#define DISHWASHERCONTROLLER_SM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "qpn.h"
#include "signals.h"
#include "constants.h"
#include "active_objects.h"

/*.$declare${AOs::Dishwasher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Dishwasher} ......................................................*/
typedef struct Dishwasher {
/* protected: */
    QActive super;
} Dishwasher;

/* protected: */
QState Dishwasher_initial(Dishwasher * const me);
QState Dishwasher_Operating(Dishwasher * const me);
QState Dishwasher_DoorClosed(Dishwasher * const me);
QState Dishwasher_TimedFill(Dishwasher * const me);
QState Dishwasher_WashCycle(Dishwasher * const me);
QState Dishwasher_RinseCycle(Dishwasher * const me);
QState Dishwasher_Idle(Dishwasher * const me);
QState Dishwasher_ManualWash(Dishwasher * const me);
QState Dishwasher_ManualRinse(Dishwasher * const me);
QState Dishwasher_DoorOpen(Dishwasher * const me);
QState Dishwasher_Fault(Dishwasher * const me);
QState Dishwasher_Startup(Dishwasher * const me);
/*.$enddecl${AOs::Dishwasher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef __cplusplus
}
#endif

#endif