/*.$file${../qm_generated::dishwasher_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_controller.qm
* File:  ${../qm_generated::dishwasher_sm.c}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::dishwasher_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "dishwasher_sm.h"
#include "bsp.h"
#include "app/dishwasher_helpers.h"

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Dishwasher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Dishwasher} ......................................................*/
/*.${AOs::Dishwasher::SM} ..................................................*/
QState Dishwasher_initial(Dishwasher * const me) {
    /*.${AOs::Dishwasher::SM::initial} */
    return Q_TRAN(&Dishwasher_state1);
}
/*.${AOs::Dishwasher::SM::state1} ..........................................*/
QState Dishwasher_state1(Dishwasher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::Dishwasher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
