#ifndef DISHWASHERCONTROLLER_SIGNALS_H
#define DISHWASHERCONTROLLER_SIGNALS_H

#include "qpn.h"

enum DishwasherSignals
{
    STARTUP_SIG = Q_USER_SIG,

    DOOR_OPEN_SIG,
    DOOR_CLOSE_SIG,
    FLOAT_OPEN_SIG,
    FLOAT_CLOSE_SIG,
    MANUALRINSE_OPEN_SIG,
    MANUALRINSE_CLOSE_SIG,
    MANUALWASH_OPEN_SIG,
    MANUALWASH_CLOSE_SIG,
    TIMEDFILL_OPEN_SIG,
    TIMEDFILL_CLOSE_SIG,
    STOP_OPEN_SIG,
    STOP_CLOSE_SIG,

    STARTUP_FAULT_SIG,
    RTD_FAULT_SIG,
    OVER_TEMP_FAULT_SIG,
};

#endif // DISHWASHERCONTROLLER_SIGNALS_H
